### ISSUE TITLE
hard coded table prefix

### ISSUE THREAD

**Issue by danmarsden** [doiphode/moodle-tool_clearbackupfiles#1]
https://github.com/doiphode/moodle-tool_clearbackupfiles/blob/master/classes/processer.php#L74

please do not hard code "mdl_" - table names should be surrounded in curly braces as per:
https://docs.moodle.org/dev/Data_manipulation_API#Table_prefix

**Comment by doiphode** [comment]
Resolved in 71fe9d8f850feeb3e7b491269320ea14a22a1a8a
