### ISSUE TITLE
All newly added backups are deleted immediately

### ISSUE THREAD

**Issue by christianabila** [doiphode/moodle-tool_clearbackupfiles#10]
https://github.com/doiphode/moodle-tool_clearbackupfiles/blob/e521f796e665fc60d9c631b7b18de859d0577c78/classes/task/cron_task.php#L48

This change immediately clears any backups made, making it basically impossible to download the files beforehand. It also makes plugins like block_sharing_cart unusable.

What's the exact purpose of this change?

Best regards,
Chris

**Comment by doiphode** [comment]
Thank you for raising this Christian.

Can I check what number of days you are giving. I can test as per your setting.

**Comment by christianabila** [comment]
Hi!

It's the default value (5).

Best regards,
Chris

**Comment by doiphode** [comment]
Hi Chris,

Can you please try the updated code and let me know?

Thank you for your time on this.

Kind regards

**Comment by christianabila** [comment]
Hi again!

That change should do the trick 😉

**Comment by christianabila** [comment]
One more thing: perhaps have the scheduled task disabled by default. It could be fatal to have all older backups deleted right after the plugin installation/update, without any consent.

**Comment by doiphode** [comment]
I have further updated the plugin. Thanks.

**Comment by doiphode** [comment]
Closing this, as the update is added.

Thanks as always!
