### ISSUE TITLE
incorrect camel case used

### ISSUE THREAD

**Issue by danmarsden** [doiphode/moodle-tool_clearbackupfiles#3]
Moodle uses sentence case - some of the strings in your lang use camel case eg:

$string['pluginname'] = 'Clear Backup Files';
$string['filename'] = 'File Name';
$string['filesize'] = 'File Size';

should be more like:
$string['pluginname'] = 'Clear backup files';
$string['filename'] = 'File name';
$string['filesize'] = 'File size';

**Comment by doiphode** [comment]
Resolved in 71fe9d8f850feeb3e7b491269320ea14a22a1a8a
