### ISSUE TITLE
Improve UX to prevent accidental loss.

### ISSUE THREAD

**Issue by danmarsden** [doiphode/moodle-tool_clearbackupfiles#4]
Clicking on a link to a setting in the navigation should not trigger a destructive process without some form of confirmation.

You should modify your index.php to display a message covering what the process will do with some big warnings to say that the process is not reversable, and then only trigger the process when someone clicks the button on the page.

**Comment by doiphode** [comment]
Resolved in 71fe9d8f850feeb3e7b491269320ea14a22a1a8a
