### ISSUE TITLE
debugging warnings

### ISSUE THREAD

**Issue by danmarsden** [doiphode/moodle-tool_clearbackupfiles#7]
Hi there - I just managed to test this again and functionally it seems to look ok, but when I deleted some backup files it triggered the following warnings:

Notice: Undefined property: tool_clearbackupfiles_processer::$clearedfiles in /www/moodle/admin/tool/clearbackupfiles/classes/processer.php on line 58

Warning: count(): Parameter must be an array or an object that implements Countable in /www/moodle/admin/tool/clearbackupfiles/classes/processer.php on line 58

any chance you could quickly drop a fix in for that and this should be ready for approval! - thanks for your patience!

**Comment by doiphode** [comment]
Hi Dan,

I have provided a fix in the latest commit.

Thank you!
