### ISSUE TITLE
Installation aborted due to validation failure

### ISSUE THREAD

**Issue by caiadogithub** [doiphode/moodle-tool_clearbackupfiles#8]
Debugging output enabled
Downloading tool_clearbackupfiles ... 
 <- https://moodle.org/plugins/download.php/28154/tool_clearbackupfiles_moodle41_2022120500.zip
 -> /XXX/XXX/temp/core_plugin/code_manager/distfiles/f6070420cc9b6fc022a0d3ab185e0886.zip ... OK
Validating tool_clearbackupfiles ... Error
  [Error] Extracted file not found [{"file":"clearbackupfiles\/.git\/refs\/tags\/"}] 
Installation aborted due to validation failure

**Comment by doiphode** [comment]
Removing the .git fodler should resolve the issue.

Please check the version I have just uploaded.
https://moodle.org/plugins/tool_clearbackupfiles/3.9-release-1/28188

**Comment by doiphode** [comment]
Closing this issue as you need to remove the .git folder.
